USE [master]
GO

/****** Object:  Database [IP3AnlagenInventar]    Script Date: 17.07.2013 21:37:23 ******/
CREATE DATABASE [IP3AnlagenInventar]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IP3AnlagenInventar', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\IP3AnlagenInventar.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'IP3AnlagenInventar_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\IP3AnlagenInventar_log.ldf' , SIZE = 2048KB , MAXSIZE = 1024000KB , FILEGROWTH = 10%)
GO

ALTER DATABASE [IP3AnlagenInventar] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IP3AnlagenInventar].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IP3AnlagenInventar] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET ARITHABORT OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [IP3AnlagenInventar] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IP3AnlagenInventar] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IP3AnlagenInventar] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET  DISABLE_BROKER 
GO

ALTER DATABASE [IP3AnlagenInventar] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IP3AnlagenInventar] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET RECOVERY FULL 
GO

ALTER DATABASE [IP3AnlagenInventar] SET  MULTI_USER 
GO

ALTER DATABASE [IP3AnlagenInventar] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IP3AnlagenInventar] SET DB_CHAINING OFF 
GO

ALTER DATABASE [IP3AnlagenInventar] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [IP3AnlagenInventar] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [IP3AnlagenInventar] SET  READ_WRITE 
GO

