<%@ Page Title="" Language="C#" MasterPageFile="~/SiteMaster/StandardMaster.Master" AutoEventWireup="true" CodeBehind="DepreciationCategoryList.aspx.cs" Inherits="Client.Site.Administrator.DepreciationCategoryList" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder" runat="server">
    <telerik:RadAjaxPanel ID="RadAjaxPanel1" runat="server">
        <telerik:RadGrid ID="rgCategories" runat="server" AutoGenerateEditColumn="True" AutoGenerateDeleteColumn="True" CellSpacing="0" GridLines="None"
            AllowPaging="True" AllowSorting="True" ShowStatusBar="true" DataSourceID="EntityDataSource1" OnItemCommand="rgCategories_ItemCommand">

            <ClientSettings>
                <Scrolling AllowScroll="True" UseStaticHeaders="True"></Scrolling>
            </ClientSettings>

            <MasterTableView DataSourceID="EntityDataSource1" DataKeyNames="DepreciationCategoryId" AutoGenerateColumns="False" AllowAutomaticDeletes="true" AllowAutomaticInserts="true" AllowAutomaticUpdates="true"
                CommandItemDisplay="Top" InsertItemPageIndexAction="ShowItemOnCurrentPage">
                <Columns>
                    <telerik:GridBoundColumn DataField="DepreciationCategoryId" ReadOnly="true" Display="false" HeaderText="DepreciationCategoryId" SortExpression="DepreciationCategoryId" UniqueName="DepreciationCategoryId" DataType="System.Int32" FilterControlAltText="Filter DepreciationCategoryId column">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Name" HeaderText="Name" SortExpression="Name" UniqueName="Name" FilterControlAltText="Filter Name column">
                    </telerik:GridBoundColumn>
                </Columns>
            </MasterTableView>

        </telerik:RadGrid>

        <asp:EntityDataSource runat="server" ID="EntityDataSource1" DefaultContainerName="IP3AnlagenInventarEntities" ConnectionString="name=IP3AnlagenInventarEntities" EnableFlattening="False" EntitySetName="DepreciationCategories" EnableDelete="True">
        </asp:EntityDataSource>
    </telerik:RadAjaxPanel>
    <telerik:RadWindowManager ID="RadWindowManager1" runat="server">
    </telerik:RadWindowManager>
    <script>
        function alertCallBackFn(arg) {

        }

    </script>
</asp:Content>
