<%@ Page Title="" Language="C#" MasterPageFile="~/SiteMaster/StandardMaster.Master" AutoEventWireup="true" CodeBehind="DepreciationCategoryList.aspx.cs" Inherits="Client.Site.Administrator.DepreciationCategoryList" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder" runat="server">
    <telerik:RadAjaxPanel ID="RadAjaxPanel1" runat="server">
        <telerik:RadGrid ID="rgCategories" runat="server" AutoGenerateEditColumn="True" AutoGenerateDeleteColumn="True" CellSpacing="0" GridLines="None"  Skin="Silk" OnPreRender="rgCategories_PreRender"
            AllowPaging="True" AllowSorting="True" ShowStatusBar="true" OnItemCommand="rgCategories_ItemCommand">

            <ClientSettings>
                <Scrolling AllowScroll="True" UseStaticHeaders="True"></Scrolling>
            </ClientSettings>

            <MasterTableView DataKeyNames="DepreciationCategoryId" AutoGenerateColumns="False" AllowAutomaticDeletes="true" AllowAutomaticInserts="true" AllowAutomaticUpdates="true"
                CommandItemDisplay="Top" InsertItemPageIndexAction="ShowItemOnCurrentPage">

                <CommandItemTemplate>
                    <div style="padding: 5px;">
                        <telerik:RadButton ID="btnNew" runat="server" CommandName="InitInsert" Text="Neue Kategorie" AutoPostBack="true"/>
                    </div>
                </CommandItemTemplate>

                <Columns>
                    <telerik:GridBoundColumn DataField="DepreciationCategoryId" ReadOnly="true" Display="false" HeaderText="DepreciationCategoryId" SortExpression="DepreciationCategoryId" UniqueName="DepreciationCategoryId" DataType="System.Int32" FilterControlAltText="Filter DepreciationCategoryId column">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Name" HeaderText="Name" SortExpression="Name" UniqueName="Name" FilterControlAltText="Filter Name column">
                    </telerik:GridBoundColumn>
                    <telerik:GridCheckBoxColumn DataField="IsDefault" HeaderText="Standard" SortExpression="IsDefault" UniqueName="IsDefault" FilterControlAltText="Filter IsDefault column">
                    </telerik:GridCheckBoxColumn>
                </Columns>
            </MasterTableView>

        </telerik:RadGrid>

    </telerik:RadAjaxPanel>
    <telerik:RadWindowManager ID="RadWindowManager1" runat="server">
    </telerik:RadWindowManager>
    <script>
        function alertCallBackFn(arg) {

        }

    </script>
</asp:Content>
