<%@ Page Title="" Language="C#" MasterPageFile="~/SiteMaster/StandardMaster.Master" AutoEventWireup="true" CodeBehind="InsuranceCategoryList.aspx.cs" Inherits="Client.Site.Administrator.InsuranceCategoryList" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder" runat="server">
    <telerik:RadAjaxPanel ID="RadAjaxPanel1" runat="server">
        <telerik:RadGrid ID="rgCategories" runat="server" AutoGenerateEditColumn="True" AutoGenerateDeleteColumn="True" CellSpacing="0" GridLines="None"
            AllowPaging="True" AllowSorting="True" ShowStatusBar="true" DataSourceID="EntityDataSource1"
            AllowAutomaticInserts="true" AllowAutomaticUpdates="true" OnItemCommand="rgCategories_ItemCommand">

            <ClientSettings>
                <Scrolling AllowScroll="True" UseStaticHeaders="True"></Scrolling>
            </ClientSettings>

            <MasterTableView DataSourceID="EntityDataSource1" DataKeyNames="InsuranceCategoryId" AutoGenerateColumns="False" AllowAutomaticDeletes="true" AllowAutomaticInserts="true" AllowAutomaticUpdates="true"
                CommandItemDisplay="Top" InsertItemPageIndexAction="ShowItemOnCurrentPage">
                <Columns>
                    <telerik:GridBoundColumn DataField="InsuranceCategoryId" Visible="false" ReadOnly="True" HeaderText="InsuranceCategoryId" SortExpression="InsuranceCategoryId" UniqueName="InsuranceCategoryId" DataType="System.Int32" FilterControlAltText="Filter InsuranceCategoryId column">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Name" HeaderText="Name" SortExpression="Name" UniqueName="Name" FilterControlAltText="Filter Name column">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Code" HeaderText="Code" SortExpression="Code" UniqueName="Code" FilterControlAltText="Filter Code column">
                    </telerik:GridBoundColumn>
                </Columns>
            </MasterTableView>

        </telerik:RadGrid>

        <asp:EntityDataSource runat="server" ID="EntityDataSource1" DefaultContainerName="IP3AnlagenInventarEntities" ConnectionString="name=IP3AnlagenInventarEntities" EnableFlattening="False" EnableInsert="True" EnableUpdate="True" EntitySetName="InsuranceCategories">
        </asp:EntityDataSource>
    </telerik:RadAjaxPanel>
    <telerik:RadWindowManager ID="RadWindowManager1" runat="server">
    </telerik:RadWindowManager>
    <script>
        function alertCallBackFn(arg) {

        }

    </script>
</asp:Content>
