<%@ Page Title="" Language="C#" MasterPageFile="~/SiteMaster/StandardMaster.Master" AutoEventWireup="true" CodeBehind="UserList.aspx.cs" Inherits="Client.Site.Administrator.UserList" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder" runat="server">
    <telerik:RadAjaxPanel ID="pnAjax" runat="server">
        <telerik:RadGrid ID="rgUsers" runat="server" AutoGenerateEditColumn="True" AutoGenerateDeleteColumn="False" CellSpacing="0" GridLines="None"  Skin="Silk" OnInit="rgUsers_Init"
            AllowPaging="True" AllowSorting="True" ShowStatusBar="true" DataSourceID="DataSource" OnItemCommand="rgUsers_ItemCommand">

            <MasterTableView DataSourceID="DataSource" AutoGenerateColumns="False" DataKeyNames="AppUserId" AllowAutomaticInserts="true" AllowAutomaticUpdates="true"
                 CommandItemDisplay="Top" InsertItemPageIndexAction="ShowItemOnCurrentPage" AllowFilteringByColumn="true">

                <CommandItemTemplate>
                    <div style="padding: 5px;">
                        <telerik:RadButton ID="btnNew" runat="server" CommandName="InitInsert" Text="Neuer Benutzer" /> </div>
                </CommandItemTemplate>

                <Columns>
                    <telerik:GridBoundColumn DataField="AppUserId" DataType="System.Int32" Display="false" FilterControlAltText="Filter AppUserId column" HeaderText="AppUserId" ReadOnly="True" SortExpression="AppUserId" UniqueName="AppUserId">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="FirstName" FilterControlAltText="Filter FirstName column" HeaderText="FirstName" SortExpression="FirstName" UniqueName="FirstName">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="LastName" FilterControlAltText="Filter LastName column" HeaderText="LastName" SortExpression="LastName" UniqueName="LastName">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Email" FilterControlAltText="Filter Email column" HeaderText="Email" SortExpression="Email" UniqueName="Email">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Domain" FilterControlAltText="Filter Domain column" HeaderText="Domain" SortExpression="Domain" UniqueName="Domain">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="UserName" HeaderText="UserName" SortExpression="UserName" UniqueName="UserName" FilterControlAltText="Filter UserName column">
                    </telerik:GridBoundColumn>
                    <telerik:GridCheckBoxColumn DataField="IsAdmin" HeaderText="IsAdmin" SortExpression="IsAdmin" UniqueName="IsAdmin" DataType="System.Boolean" FilterControlAltText="Filter IsAdmin column"></telerik:GridCheckBoxColumn>
                    <telerik:GridButtonColumn UniqueName="btnLogin" ButtonType="LinkButton" CommandName="Login" ButtonCssClass="GridEventButton" ItemStyle-HorizontalAlign="Right" HeaderStyle-HorizontalAlign="Right" Text="Login">
                     </telerik:GridButtonColumn>
                    <telerik:GridButtonColumn UniqueName="btnDelete" ButtonType="LinkButton" CommandName="Delete" ButtonCssClass="GridEventButton" ItemStyle-HorizontalAlign="Right" HeaderStyle-HorizontalAlign="Right" Text="Delete"
                        ConfirmDialogType="RadWindow" ConfirmText="Sind Sie sicher dass Sie den User entfernen wollen?" ConfirmTitle="Benutzer entfernen">
                     </telerik:GridButtonColumn>
                </Columns>
            </MasterTableView>

        </telerik:RadGrid>
    </telerik:RadAjaxPanel>
    <telerik:RadWindowManager ID="RadWindowManager1" runat="server">
    </telerik:RadWindowManager>
    <script>
        function alertCallBackFn(arg) {

        }

    </script>
    <asp:EntityDataSource ID="DataSource" runat="server" ConnectionString="name=IP3AnlagenInventarEntities" DefaultContainerName="IP3AnlagenInventarEntities" EnableDelete="True" EnableFlattening="False" EnableInsert="True" EnableUpdate="True" EntitySetName="AppUsers"></asp:EntityDataSource>
</asp:Content>
