<%@ Page Title="" Language="C#" MasterPageFile="~/SiteMaster/StandardMaster.Master" AutoEventWireup="true" CodeBehind="UserList.aspx.cs" Inherits="Client.Site.Administrator.UserList" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder" runat="server">
    <telerik:RadAjaxPanel ID="pnAjax" runat="server">
        <telerik:RadGrid ID="rgUsers" runat="server" AutoGenerateEditColumn="True" AutoGenerateDeleteColumn="True" CellSpacing="0" GridLines="None"
            AllowPaging="True" AllowSorting="True" ShowStatusBar="true" DataSourceID="DataSource" OnItemCommand="rgUsers_ItemCommand">

            <MasterTableView DataSourceID="DataSource" AutoGenerateColumns="False" DataKeyNames="AppUserId" AllowAutomaticInserts="true" AllowAutomaticUpdates="true"
                 CommandItemDisplay="Top" InsertItemPageIndexAction="ShowItemOnCurrentPage">

                <Columns>
                    <telerik:GridBoundColumn DataField="AppUserId" DataType="System.Int32" Display="false" FilterControlAltText="Filter AppUserId column" HeaderText="AppUserId" ReadOnly="True" SortExpression="AppUserId" UniqueName="AppUserId">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="FirstName" FilterControlAltText="Filter FirstName column" HeaderText="FirstName" SortExpression="FirstName" UniqueName="FirstName">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="LastName" FilterControlAltText="Filter LastName column" HeaderText="LastName" SortExpression="LastName" UniqueName="LastName">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Email" FilterControlAltText="Filter Email column" HeaderText="Email" SortExpression="Email" UniqueName="Email">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Domain" FilterControlAltText="Filter Domain column" HeaderText="Domain" SortExpression="Domain" UniqueName="Domain">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="UserName" HeaderText="UserName" SortExpression="UserName" UniqueName="UserName" FilterControlAltText="Filter UserName column">
                    </telerik:GridBoundColumn>
                    <telerik:GridCheckBoxColumn DataField="IsAdmin" HeaderText="IsAdmin" SortExpression="IsAdmin" UniqueName="IsAdmin" DataType="System.Boolean" FilterControlAltText="Filter IsAdmin column"></telerik:GridCheckBoxColumn>
                </Columns>
            </MasterTableView>

        </telerik:RadGrid>
    </telerik:RadAjaxPanel>
    <asp:EntityDataSource ID="DataSource" runat="server" ConnectionString="name=IP3AnlagenInventarEntities" DefaultContainerName="IP3AnlagenInventarEntities" EnableDelete="True" EnableFlattening="False" EnableInsert="True" EnableUpdate="True" EntitySetName="AppUsers"></asp:EntityDataSource>
</asp:Content>
