//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depreciation
    {
        public Depreciation()
        {
            this.Articles = new HashSet<Article>();
        }
    
        public int DepreciationId { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> AdditionalStartDate { get; set; }
        public Nullable<System.DateTime> AdditionalEndDate { get; set; }
        public Nullable<int> DepreciationCategoryId { get; set; }
        public Nullable<int> ArticleId { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual Article Article { get; set; }
        public virtual DepreciationCategory DepreciationCategory { get; set; }
    }
}
