//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Floor
    {
        public Floor()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int FloorId { get; set; }
        public string Name { get; set; }
        public int BuildingId { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
