//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCategory
    {
        public InsuranceCategory()
        {
            this.Articles = new HashSet<Article>();
        }
    
        public int InsuranceCategoryId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
    }
}
