//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredefinedFilter
    {
        public PredefinedFilter()
        {
            this.FilterFields = new HashSet<FilterField>();
        }
    
        public int PredefinedFilterId { get; set; }
        public Nullable<bool> FilterName { get; set; }
    
        public virtual ICollection<FilterField> FilterFields { get; set; }
    }
}
