//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierBranch
    {
        public SupplierBranch()
        {
            this.Articles = new HashSet<Article>();
        }
    
        public int SupplierBranchId { get; set; }
        public string Country { get; set; }
        public string Place { get; set; }
        public string ZipCode { get; set; }
        public int SupplierId { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
